package com.example.thumbnailfiles;

import android.app.*;
import android.os.*;
import android.content.*;
import android.database.Cursor;
import android.graphics.*;
import android.media.MediaMetadataRetriever;
import android.net.Uri;
import android.provider.DocumentsContract;
import android.view.*;
import android.widget.*;
import java.util.*;
import java.util.concurrent.*;

public class MainActivity extends Activity {
  static final int PICK_TREE=1,PICK_IMAGE=2;
  SharedPreferences prefs;
  Uri tree,folder,editing;
  LinearLayout root,toolbar,tiles;
  ScrollView scroll;
  int columns=2, generation=0;
  boolean list=false;
  final Handler main=new Handler(Looper.getMainLooper());
  final ExecutorService worker=Executors.newSingleThreadExecutor();
  final android.util.LruCache<String,Bitmap> cache=new android.util.LruCache<String,Bitmap>(24*1024){
    protected int sizeOf(String k,Bitmap b){return b.getByteCount()/1024;}
  };
  final ArrayList<Preview> previews=new ArrayList<>();
  Preview active;
  VideoView player;
  int dp(float v){return (int)(v*getResources().getDisplayMetrics().density+.5f);}
  static class Item {Uri uri;String name,mime;boolean dir;Item(Uri u,String n,String m,boolean d){uri=u;name=n;mime=m;dir=d;}}
  static class Preview {Item item;FrameLayout cell;ImageView image;Preview(Item i,FrameLayout c,ImageView v){item=i;cell=c;image=v;}}
  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("settings",0);columns=prefs.getInt("cols",2);list=prefs.getBoolean("list",false);String saved=prefs.getString("tree",null);if(saved!=null){try{tree=Uri.parse(saved);folder=DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));}catch(Exception ignored){tree=null;folder=null;}}show();}
  TextView button(String label,Runnable action){TextView t=new TextView(this);t.setText(label);t.setTextSize(15);t.setTextColor(Color.WHITE);t.setPadding(dp(12),dp(12),dp(12),dp(12));t.setOnClickListener(v->action.run());return t;}
  void stopPlayer(){if(player!=null){try{player.stopPlayback();if(active!=null)active.cell.removeView(player);}catch(Exception ignored){}player=null;}active=null;}
  void show(){generation++;stopPlayer();previews.clear();root=new LinearLayout(this);root.setOrientation(1);root.setBackgroundColor(0xff10151e);setContentView(root);toolbar=new LinearLayout(this);toolbar.setBackgroundColor(0xff202b3a);root.addView(toolbar);toolbar.addView(button("◀",()->up()));toolbar.addView(button("Choose folder",()->{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);startActivityForResult(i,PICK_TREE);}));toolbar.addView(button(list?"Grid":"List",()->{list=!list;prefs.edit().putBoolean("list",list).apply();show();}));toolbar.addView(button("Size",()->{columns=columns==4?2:columns+1;prefs.edit().putInt("cols",columns).apply();show();}));scroll=new ScrollView(this);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));tiles=new LinearLayout(this);tiles.setPadding(dp(5),dp(5),dp(5),dp(5));tiles.setOrientation(1);scroll.addView(tiles);scroll.setOnScrollChangeListener((View.OnScrollChangeListener)(v,x,y,ox,oy)->updateVisible());if(folder==null){tiles.addView(button("Choose a folder above to start browsing videos.",()->{}));return;}tiles.addView(button("Loading folder…",()->{}));load(generation,tree,folder);}
  void load(int token,Uri selectedTree,Uri selectedFolder){worker.execute(()->{ArrayList<Item> items=new ArrayList<>();String error=null;try{Uri children=DocumentsContract.buildChildDocumentsUriUsingTree(selectedTree,DocumentsContract.getDocumentId(selectedFolder));try(Cursor c=getContentResolver().query(children,new String[]{DocumentsContract.Document.COLUMN_DOCUMENT_ID,DocumentsContract.Document.COLUMN_DISPLAY_NAME,DocumentsContract.Document.COLUMN_MIME_TYPE},null,null,null)){if(c!=null)while(c.moveToNext()){String id=c.getString(0),name=c.getString(1),mime=c.getString(2);boolean dir=DocumentsContract.Document.MIME_TYPE_DIR.equals(mime);if(dir||(mime!=null&&mime.startsWith("video/")))items.add(new Item(DocumentsContract.buildDocumentUriUsingTree(selectedTree,id),name==null?"Untitled":name,mime,dir));}}Collections.sort(items,(a,b)->a.dir!=b.dir?(a.dir?-1:1):a.name.compareToIgnoreCase(b.name));}catch(Exception e){error=e.getMessage();}final String err=error;main.post(()->{if(token!=generation||isFinishing()||isDestroyed())return;tiles.removeAllViews();if(err!=null){tiles.addView(button("Cannot read folder: "+err,()->{}));return;}render(items,token);});});}
  void render(ArrayList<Item> items,int token){int count=list?1:columns;LinearLayout row=null;for(int i=0;i<items.size();i++){if(i%count==0){row=new LinearLayout(this);tiles.addView(row);}Item it=items.get(i);FrameLayout cell=new FrameLayout(this);LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(0,dp(list?90:190),1);cp.setMargins(dp(3),dp(3),dp(3),dp(3));row.addView(cell,cp);cell.setBackgroundColor(0xff253244);if(it.dir){cell.setOnClickListener(v->{folder=it.uri;show();});}else{ImageView cover=new ImageView(this);cover.setScaleType(ImageView.ScaleType.CENTER_CROP);cell.addView(cover,new FrameLayout.LayoutParams(-1,-1));previews.add(new Preview(it,cell,cover));cell.setOnClickListener(v->{Intent in=new Intent(Intent.ACTION_VIEW);in.setDataAndType(it.uri,it.mime);in.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);try{startActivity(in);}catch(Exception e){Toast.makeText(this,"No video player found",Toast.LENGTH_SHORT).show();}});cell.setOnLongClickListener(v->{edit(it);return true;});}TextView title=new TextView(this);title.setText((it.dir?"📁 ":"")+it.name);title.setTextColor(Color.WHITE);title.setTextSize(12);title.setMaxLines(2);title.setBackgroundColor(0xbb111822);cell.addView(title,new FrameLayout.LayoutParams(-1,-2,Gravity.BOTTOM));}scroll.post(()->updateVisible());}
  String key(Uri u,String suffix){return u.toString()+"/"+suffix;}
  void updateVisible(){if(scroll==null)return;int top=scroll.getScrollY(),bottom=top+scroll.getHeight();Preview candidate=null;for(Preview p:previews){int y=positionInTiles(p.cell);boolean visible=y+p.cell.getHeight()>top-dp(190)&&y<bottom+dp(190);if(visible){if(p.image.getDrawable()==null)requestThumbnail(p,generation);if(candidate==null&&y+p.cell.getHeight()>top&&y<bottom&&prefs.getBoolean(key(p.item.uri,"animate"),true))candidate=p;}}if(candidate!=active)startPlayer(candidate);}
  int positionInTiles(View v){int y=0;View child=v;while(child!=null&&child!=tiles){y+=child.getTop();android.view.ViewParent parent=child.getParent();child=parent instanceof View?(View)parent:null;}return y;}
  final HashSet<String> pending=new HashSet<>();
  void requestThumbnail(Preview p,int token){String custom=prefs.getString(key(p.item.uri,"cover"),null);String k=p.item.uri.toString()+"|"+custom;Bitmap cached=cache.get(k);if(cached!=null){p.image.setImageBitmap(cached);return;}if(pending.contains(k))return;pending.add(k);worker.execute(()->{Bitmap bitmap=null;try{if(custom!=null){try(android.os.ParcelFileDescriptor fd=getContentResolver().openFileDescriptor(Uri.parse(custom),"r")){if(fd!=null){BitmapFactory.Options o=new BitmapFactory.Options();o.inJustDecodeBounds=true;BitmapFactory.decodeFileDescriptor(fd.getFileDescriptor(),null,o);o.inSampleSize=Math.max(1,Math.max(o.outWidth/320,o.outHeight/320));o.inJustDecodeBounds=false;bitmap=BitmapFactory.decodeFileDescriptor(fd.getFileDescriptor(),null,o);}}}else{MediaMetadataRetriever r=new MediaMetadataRetriever();try{r.setDataSource(this,p.item.uri);if(Build.VERSION.SDK_INT>=27)bitmap=r.getScaledFrameAtTime(0,MediaMetadataRetriever.OPTION_CLOSEST_SYNC,320,240);else bitmap=r.getFrameAtTime(0,MediaMetadataRetriever.OPTION_CLOSEST_SYNC);}finally{r.release();}}}catch(Exception ignored){}final Bitmap result=bitmap;main.post(()->{pending.remove(k);if(result!=null)cache.put(k,result);if(token==generation&&previews.contains(p)&&result!=null)p.image.setImageBitmap(result);});});}
  void startPlayer(Preview p){stopPlayer();if(p==null||!hasWindowFocus())return;active=p;VideoView v=new VideoView(this);player=v;FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(-1,-1);p.cell.addView(v,1,lp);long start=prefs.getLong(key(p.item.uri,"start"),0),end=prefs.getLong(key(p.item.uri,"end"),5000);v.setOnPreparedListener(mp->{if(player!=v)return;mp.setVolume(0,0);mp.setLooping(false);int duration=mp.getDuration();if(duration<=0)return;int s=(int)Math.min(start,Math.max(0,duration-200));v.seekTo(s);v.start();scheduleLoop(v,s,(int)Math.min(Math.max(end,s+200),duration));});v.setOnErrorListener((mp,what,extra)->{if(player==v)stopPlayer();return true;});try{v.setVideoURI(p.item.uri);}catch(Exception e){stopPlayer();}}
  void scheduleLoop(VideoView v,int start,int end){main.postDelayed(()->{if(player!=v||isFinishing()||isDestroyed())return;if(v.isPlaying()&&v.getCurrentPosition()>=end)v.seekTo(start);scheduleLoop(v,start,end);},250);}
  void edit(Item it){editing=it.uri;LinearLayout layout=new LinearLayout(this);layout.setOrientation(1);layout.setPadding(dp(20),dp(8),dp(20),0);EditText from=new EditText(this),to=new EditText(this);from.setInputType(8194);to.setInputType(8194);from.setHint("Start seconds");to.setHint("End seconds");from.setText(String.valueOf(prefs.getLong(key(it.uri,"start"),0)/1000f));to.setText(String.valueOf(prefs.getLong(key(it.uri,"end"),5000)/1000f));layout.addView(from);layout.addView(to);CheckBox animate=new CheckBox(this);animate.setText("Autoplay thumbnail");animate.setChecked(prefs.getBoolean(key(it.uri,"animate"),true));layout.addView(animate);Button image=new Button(this);image.setText("Choose custom cover image");layout.addView(image);image.setOnClickListener(v->{Intent in=new Intent(Intent.ACTION_OPEN_DOCUMENT);in.setType("image/*");in.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(in,PICK_IMAGE);});new AlertDialog.Builder(this).setTitle(it.name).setView(layout).setPositiveButton("Save",(d,w)->{try{long s=(long)(Float.parseFloat(from.getText().toString())*1000),e=(long)(Float.parseFloat(to.getText().toString())*1000);if(s<0||e<=s)throw new Exception();prefs.edit().putLong(key(it.uri,"start"),s).putLong(key(it.uri,"end"),e).putBoolean(key(it.uri,"animate"),animate.isChecked()).apply();show();}catch(Exception ex){Toast.makeText(this,"End must be greater than start",Toast.LENGTH_LONG).show();}}).setNegativeButton("Cancel",null).show();}
  @Override protected void onActivityResult(int req,int result,Intent data){super.onActivityResult(req,result,data);if(result!=RESULT_OK||data==null)return;Uri uri=data.getData();if(uri==null)return;if(req==PICK_TREE){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}tree=uri;folder=DocumentsContract.buildDocumentUriUsingTree(tree,DocumentsContract.getTreeDocumentId(tree));prefs.edit().putString("tree",uri.toString()).apply();show();}else if(req==PICK_IMAGE&&editing!=null){try{getContentResolver().takePersistableUriPermission(uri,Intent.FLAG_GRANT_READ_URI_PERMISSION);}catch(Exception ignored){}prefs.edit().putString(key(editing,"cover"),uri.toString()).apply();show();}}
  void up(){if(folder!=null&&tree!=null&&!DocumentsContract.getDocumentId(folder).equals(DocumentsContract.getTreeDocumentId(tree))){String id=DocumentsContract.getDocumentId(folder);int p=id.lastIndexOf('/');folder=DocumentsContract.buildDocumentUriUsingTree(tree,p>=0?id.substring(0,p):DocumentsContract.getTreeDocumentId(tree));show();}}
  @Override public void onBackPressed(){if(tree!=null&&folder!=null&&!DocumentsContract.getDocumentId(folder).equals(DocumentsContract.getTreeDocumentId(tree)))up();else super.onBackPressed();}
  @Override protected void onPause(){super.onPause();stopPlayer();}
  @Override protected void onResume(){super.onResume();if(scroll!=null)scroll.post(()->updateVisible());}
  @Override protected void onDestroy(){generation++;stopPlayer();worker.shutdownNow();super.onDestroy();}
}
